import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByText('Job', { exact: true }).click();
  await page.getByRole('menuitem', { name: 'Job Titles' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('Test Job Title');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Test Job Title Description');
  await page.getByText('Browse').click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('.gitconfig');
  await page.getByText('Browse').click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Screenshot 2026-04-08 182851.png');
  await page.getByRole('textbox', { name: 'Add note' }).click();
  await page.getByRole('textbox', { name: 'Add note' }).fill('Add Notes');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('row', { name: ' Test Job Title Test Job' }).click();
  await page.locator('div:nth-child(28) > .oxd-table-row > div:nth-child(4) > .oxd-table-cell-actions > button:nth-child(2)').click();
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Test Job Title Description Updated');
  await page.getByRole('textbox', { name: 'Add note' }).click();
  await page.getByRole('textbox', { name: 'Add note' }).fill('Add Notes Updated');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('div:nth-child(28) > .oxd-table-row > div:nth-child(4) > .oxd-table-cell-actions > button').first().click();
  await page.getByRole('button', { name: ' Yes, Delete' }).click();
  await page.getByText('User Management').click();
  await page.getByRole('menuitem', { name: 'Users' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('.oxd-icon.bi-caret-down-fill.oxd-select-text--arrow').first().click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('d');
  await page.getByRole('option', { name: 'A8DCo 4Ys 010Z' }).click();
  await page.locator('div:nth-child(3) > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
  await page.getByText('Enabled').click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('fsfsfsqws');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('@!Game149');
  await page.getByRole('textbox').nth(3).press('Tab');
  await page.getByRole('textbox').nth(4).press('Tab');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('@!Game149');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers');
  await page.locator('div:nth-child(6) > .oxd-table-row > div:nth-child(6) > .oxd-table-cell-actions > button:nth-child(2)').click();
  await page.locator('div:nth-child(3) > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
  await page.getByRole('option', { name: 'Disabled' }).click();
  await page.getByText('Edit UserUser').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('div:nth-child(6) > .oxd-table-row > div:nth-child(6) > .oxd-table-cell-actions > button').first().click();
  await page.getByRole('button', { name: ' Yes, Delete' }).click();
  await page.locator('span').filter({ hasText: 'mandag4 userg4g' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});